name: iamf-tools-builder

description: Run unit tests for IAMF Tools.

inputs:
  platform:
    description: "The platform to build for."
    type: string
    default: linux

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        # Run all unit tests.
        bazelisk test -c opt  --test_output=errors iamf/...

